<?php if ($this->message): ?>
    <div class="ui-state-highlight ui-corner-all message">
        <span class="ui-icon ui-icon-info"></span>
        <ul>
            <li><?php echo $this->translate($this->message)?></li>
        </ul>
    </div>
<?php else:?>
<?php $optionTable = new Tri_Db_Table('exercise_option'); ?>
<div class="reply">
    <h3><?php echo $this->exercise->name?></h3>
    <?php if (count($this->questions)): ?>
        <ol>
            <?php foreach($this->questions as $question):?>
                <li>
                    <?php echo $question->description?> |
                    <strong><?php echo $this->translate('value')?>: <?php echo $question->note?></strong>
                    <?php if ($question->type == 'text'):?>
                        <p>
                            <?php
                                foreach($this->texts as $text) {
                                    if ($text->exercise_question_id == $question->id) {
                                        echo "<p>" . $text->value . "</p>";
                                        echo "<strong>" . $this->translate('Comment') .":</strong><br />";
                                        echo $text->comment;
                                        break;
                                    }
                                }
                            ?>
                        </p>
                    <?php else: ?>
                        <?php $optionTable = new Tri_Db_Table('exercise_option');
                              $options = $optionTable->fetchAll(array('exercise_question_id = ?' => $question->id)); ?>
                        <?php if (count($options)): ?>
                            <ul>
                                <?php foreach($options as $option):?>
                                    <?php
                                        $className = null;
                                        foreach($this->answers as $answer) {
                                            if ($option->id == $answer->exercise_option_id) {
                                                $className = $option->status;
                                            }
                                        }
                                    ?>
                                    <li class="<?php echo $className?>">
                                        &nbsp; <?php echo $option->description?>
                                        (<?php echo $this->translate($option->status)?>)
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        <?php endif; ?>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ol>
        <p><strong><?php echo $this->translate('Note')?>: <?php echo $this->note->note?></strong></p>
    <?php endif; ?>

     <?php if (count($this->notes)): ?>
        <h3><?php echo $this->translate('previous')?></h3>
        <table class="datatable">
            <tr>
                <th><?php echo $this->translate('ID')?></th>
                <th><?php echo $this->translate('Date')?></th>
            </tr>
            <?php foreach($this->notes as $note):?>
                <tr>
                    <td><?php echo $note->id;?></td>
                    <td><?php echo $this->ajax($this->date($note->created, true), 'exercise/correction/view/id/'. $note->id.'/userId/'.$this->userId)?></td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php endif; ?>
</div>
<?php endif;?>