<h3><?php echo $this->translate('Select a type')?>:</h3>
<div id="question-type">
    <div>
        <?php echo $this->translate('Multichoice')?><br />
        <a href="exercise/question/form/type/multi-choice">
            <img src="static/exercise/public/img/multichoice.png" />
        </a>
    </div>
    <div>
        <?php echo $this->translate('Multiselect')?><br />
        <a href="exercise/question/form/type/multi-select">
            <img src="static/exercise/public/img/multiselect.png" />
        </a>
    </div>
    <div>
        <?php echo $this->translate('True or false')?><br />
        <a href="exercise/question/form/type/true-false">
            <img src="static/exercise/public/img/true-false.png" />
        </a>
    </div>
    <div>
        <?php echo $this->translate('Text')?><br />
        <a href="exercise/question/form/type/text">
            <img src="static/exercise/public/img/text.png" />
        </a>
    </div>
</div>
<script>
    $('#question-type a').click(function(){
        $(this).parents('.content').load(this.href);
        return false;
    });
</script>